import { images } from "../../constants"; //Internal
import { COLORS } from "../theme";

const summaryIcon = {
  Payment_Approved: {
    icon: images.approve,
  },
  Pending_Approval: {
    icon: images.pending,
  },
  Need_Information: { icon: images.needinfo },
  Receipt_Submitted: { icon: images.submitReceipt },
};
const colorObj = {
  RECEIPT_ACCEPTED: {
    color: "#F2F0F9",
    dotColor: "#6E6893",
  },
  REJECTED: {
    color: "#FFE0E0",
    dotColor: "#D30000",
  },
  RECEIPT_SUBMITTED: {
    color: "#F2F0F9",
    dotColor: "#6E6893",
  },
  PARTIALLY_APPROVED: {
    color: "#D6E4EC",
    dotColor: "#85949F",
  },
  NEED_INFO: {
    color: "#FFE9DB",
    dotColor: "#FF914D",
  },
  PAYMENT_ELIGIBLE: {
    color: "#CCF3F5",
    dotColor: "#00C2CB",
  },
  AWAITING_APPROVAL: {
    color: "#D6E4EC",
    dotColor: "#85949F",
  },
  DELETED: {
    color: "#FFE0E0",
    dotColor: "#D30000",
  },
};
const filterObj = {
  Requester: [
    {
      tittle: "Categories",
      type: "select",
      icon: images.down,
      count: 0,
      method: 0,
    },
    {
      tittle: "Status",
      type: "select",
      icon: images.down,
      count: 0,
      method: 1,
    },
    {
      tittle: "Project_name",
      icon: images.searchFilter,
      count: 0,
    },
    {
      tittle: "Expense_ID",
      icon: images.searchFilter,
      count: 0,
    },
  ],
  Approver: [
    {
      tittle: "DepartMent",
      type: "select",
      icon: images.down,
      count: 0,
      method: 2,
    },
    {
      tittle: "Categories",
      type: "select",
      icon: images.down,
      count: 0,
      method: 3,
    },
    {
      tittle: "EmployeeName",
      icon: images.searchFilter,
      icon: images.searchFilter,
      count: 0,
    },
    {
      tittle: "Status",
      type: "select",
      icon: images.down,
      count: 0,
      method: 4,
    },
    {
      tittle: "Project_name",
      icon: images.searchFilter,
      count: 0,
    },
    {
      tittle: "Expense_ID",
      icon: images.searchFilter,
      count: 0,
    },
  ],
};
const searchData = {
  projectNames: [
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 0,
      isProjectSelected: false,
      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 0",
      requestId: "EX00010",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "abc",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 1,
      isProjectSelected: false,

      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 1",
      requestId: "EX00011",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "xyz",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 2,
      isProjectSelected: false,

      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 2",
      requestId: "EX00012",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "cook",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
  ],
  expenseId: [
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 0,

      isExpenseSelected: false,

      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 0",
      requestId: "EX00010",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "abc",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 1,
      isExpenseSelected: false,
      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 1",
      requestId: "EX00011",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "xyz",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 2,
      isExpenseSelected: false,
      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 2",
      requestId: "EX00012",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "cook",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
  ],
  employeeNames: [
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 0,
      isEmployeesSelected: false,
      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 0",
      requestId: "EX00010",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "abc",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 1,
      isEmployeesSelected: false,
      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 1",
      requestId: "EX00011",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "xyz",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
    {
      allowed_actions: [],
      expenseCategory: "Category 3",
      id: 2,
      isEmployeesSelected: false,
      last_updated_date: "string",
      organizationId: 0,
      project_name: "corona 2",
      requestId: "EX00012",
      requestedAmount: 0,
      requesterId: 0,
      requester_department: "string",
      requester_name: "cook",
      spend_category_icon_name: "string",
      status: "Payment Eligible",
    },
  ],
};
export default {
  colorObj,
  filterObj,
  searchData,
  summaryIcon,
};
