import { NetworkProvider } from "../Utilities/NetworkProvider";
import {
  authSignup,
  authOtp,
  authOtpValidation,
  authPassword,
  authLogin,
  authEmail,
  authChangePassword,
  authPersonalDetails,
  authEmirates,
  authUsernameedit,
  SSE,
  getOrganization,
  getOwnerUserData,
  getCard,
  setCardPin,
  getUserDetails,
  otpGenrate,
  otpValidation,
  updateUserdetails,
  updateEmirates,
  updateAddress,
  settingsTradeLicense,
  newPasswordSet,
  adminDelete,
  userCreation,
  getUserlist,
  markOwnerAsAdmin,
  onboardingEmiratesIdentity,
  getShareholderList,
  shareHolderDelete,
  updateShareHolders,
  registerSSEUserOnBoard,
  createAccount,
  onBoardingOwnerUserAddress,
  triggerSSEForCreateAccount,
  authMobileOtpValidation,
  adminReplace,
  emailUpdate,
  SSE_URL,
  addnewAdmin,

  //Expense API Calls
  getRequestList,
  getApproverList,
  updateExpenseStatus,
} from "./apiCalls";
import Loader from "./Loader";
import {
  setBiometric,
  getBiometric,
  setUserInformation,
  getUserInformation,
  setPagestatus,
  getPagestatus,
  getbiometricPassword,
  setbiometricPassword,
  //Expense Local data
  //Expense Recent search Local data Requester
  setActiveProjectRecentSearch,
  getActiveProjectRecentSearch,
  setCloseProjectRecentSearch,
  getCloseProjectRecentSearch,
  setActiveExpenseIdSearch,
  getActiveExpenseIdSearch,
  setCloseExpenseIdSearch,
  getCloseExpenseIdSearch,
  //Expense Recent search Local data Approver
  setApproverActiveProjectNameSearch,
  getApproverActiveProjectNameSearch,
  setApproverCloseProjectNameSearch,
  getApproverCloseProjectNameSearch,
  setActiveApproverExpenseIdSearch,
  getActiveApproverExpenseIdSearch,
  setCloseApproverExpenseIdSearch,
  getCloseApproverExpenseIdSearch,
  setActiveApproverEmployeeNameSearch,
  getActiveApproverEmployeeNameSearch,
  setCloseApproverEmployeeNameSearch,
  getCloseApproverEmployeeNameSearch
} from "./LocalStorage";
import {
  getDateToString,
  numaricValdation,
  isResponseisValid,
  isValidEmail,
  specialCharaterValidation,
  stringValdation,
  passWordValidation,
  isPlatformFileValidation,
  checkUndefined,
  currencyFormat,
  spaceCamel,
  digitFormat
} from "./utils";
import OfflineNotice from "./OfflineNotice";
import { URL } from "./config";
import { pageValidation } from "./onBoardingPageValidation";
export {
  NetworkProvider,
  OfflineNotice,
  authSignup,
  authOtp,
  authEmail,
  authOtpValidation,
  authPassword,
  authLogin,
  authChangePassword,
  Loader,
  setBiometric,
  getBiometric,
  setUserInformation,
  getUserInformation,
  authEmirates,
  authPersonalDetails,
  getDateToString,
  authUsernameedit,
  SSE,
  getOrganization,
  setPagestatus,
  getPagestatus,
  URL,
  getCard,
  setCardPin,
  numaricValdation,
  isResponseisValid,
  isValidEmail,
  specialCharaterValidation,
  stringValdation,
  otpGenrate,
  otpValidation,
  updateUserdetails,
  updateEmirates,
  updateAddress,
  settingsTradeLicense,
  newPasswordSet,
  adminDelete,
  userCreation,
  markOwnerAsAdmin,
  getUserDetails,
  adminReplace,
  emailUpdate,
  getUserlist,
  SSE_URL,
  getShareholderList,
  shareHolderDelete,
  getOwnerUserData,
  pageValidation,
  updateShareHolders,
  onboardingEmiratesIdentity,
  registerSSEUserOnBoard,
  createAccount,
  onBoardingOwnerUserAddress,
  triggerSSEForCreateAccount,
  authMobileOtpValidation,
  passWordValidation,
  isPlatformFileValidation,
  getbiometricPassword,
  setbiometricPassword,
  addnewAdmin,
  checkUndefined,
  //Expense API Calls
  getRequestList,
  getApproverList,
  updateExpenseStatus,
  currencyFormat,
  spaceCamel,
  digitFormat,
   //Expense Recent search Local data Requester
   setActiveProjectRecentSearch,
   getActiveProjectRecentSearch,
   setCloseProjectRecentSearch,
   getCloseProjectRecentSearch,
   setActiveExpenseIdSearch,
   getActiveExpenseIdSearch,
   setCloseExpenseIdSearch,
   getCloseExpenseIdSearch,
   //Expense Recent search Local data Approver
   setApproverActiveProjectNameSearch,
   getApproverActiveProjectNameSearch,
   setApproverCloseProjectNameSearch,
   getApproverCloseProjectNameSearch,
   setActiveApproverExpenseIdSearch,
   getActiveApproverExpenseIdSearch,
   setCloseApproverExpenseIdSearch,
   getCloseApproverExpenseIdSearch,
   setActiveApproverEmployeeNameSearch,
   getActiveApproverEmployeeNameSearch,
   setCloseApproverEmployeeNameSearch,
   getCloseApproverEmployeeNameSearch
};
